### ISSUE TITLE
Nano-style on-screen help by default

### ISSUE THREAD

**Issue by frankier** [darkhz/bluetuith#33]
Thanks a lot for the project. It's already at the top end of Linux bluetooth interfaces I have used in terms of comfort for me. I wonder whether it would be possible to display the keybindings by default like nano does? An equivalent of `-x` and `set nohelp` could be added.

**Comment by darkhz** [comment]
It can be implemented, but my only concern is that is could eat up screen space, especially since there are a lot of keybindings for a single screen. Wouldn't pressing the `Help` key suffice?

**Comment by frankier** [comment]
For me, I am occasionally using this software and so will never remember the keybindings. Of course if you prefer to put the bindings behind a help key that's still more convenient than reading documentation, but while it is very much your choice, I would make attempt to make an argument that the common user is a less frequent users and would thus be best served by the nano-style on-screen help that is easily hidable.

**Comment by darkhz** [comment]
Fair argument, and I will consider implementing this. As stated before, since there are a lot of keybindings for just one screen, and I do not want to use screen space unnecessarily, this will require some contemplation.

Maybe the main/commonly used keybindings to facilitate basic operations can be suggested to the user for each screen, I will have to check and run some tests. If you have any ideas on how to implement this, preferably with a PR or screenshots, do submit them, as they can be helpful in implementing this feature.

**Comment by hacktail** [comment]
I believe nothing more than navigation, connect/disconnect, the menu ( shortcuts? Well the bindings to show the menus ) and ofcourse the help binding should be shown.

The nagivation buttons should be concise as they will otherwise take up a huge amount of space; possibly it could be shown as this: `←/↓/↑/→ =  h/j/k/l` or possibly `←h/↓j/↑k/→l` or maybe replace the arrows with `L D U R` incase we shouldn't use unicode.
maybe we could display the arrows/letters/words under the bindings, like on another row?
```
h j k l
< ^ ˇ >

**Comment by darkhz** [comment]
![ksnip_20231228-151843](https://github.com/darkhz/bluetuith/assets/44058754/f146f4c0-49e2-49b0-a750-757a57641066)
@frankier @hacktail, how does this look? Would this suffice? A similar set of limited help keybindings will be present on the file picker and the progress view as well.

**Comment by hacktail** [comment]
> ![ksnip_20231228-151843](https://github.com/darkhz/bluetuith/assets/44058754/f146f4c0-49e2-49b0-a750-757a57641066)
> @frankier @hacktail, how does this look? Would this suffice? A similar set of limited help keybindings will be present on the file picker and the progress view as well.

Looks amazing

**Comment by darkhz** [comment]
This will be implemented in the next release, and any modifications to the help display can be further suggested by reopening this issue once it is closed.

**Comment by darkhz** [comment]
This feature has now been implemented and enabled by default, and can be disabled by:
- Using the command-line option `--no-help-display`
- Setting the configuration parameter `no-help-display: true`

**Comment by frankier** [comment]
Thanks a lot. It looks great!
